spring.datasource.url=jdbc:postgresql://localhost:5432/TicketPlusDB
spring.datasource.username=postgres
spring.datasource.password=@TicketPlus2026!

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=9DxMqNI1ESgaloOlyuNN/eaC+8Qzu6eMeS5o3Kz8Gj0=
app.jwt.expiration=86400000

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE

# \u2500\u2500\u2500 HTTPS / SSL \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500
server.port=8443
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=ticketplus123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=ticketplus
server.ssl.enabled=true