spring.datasource.url=jdbc:postgresql://localhost:5432/TicketPlusServer
spring.datasource.username=postgres
spring.datasource.password=@TicketPlus2026!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true